AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'spec/**/*'
Style/LineLength:
  Enabled: false
Style/FileName:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/Encoding:
  Enabled: false
Documentation:
  Enabled: false
Style/MethodLength:
  Max: 15
